spring:
  application:
    name: estudiantes
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: admin
  jpa:
    generate-ddl: 'false'
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  sql:
    init:
      data-locations: classpath:db/query.sql
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  api-docs:
    path: /api-docs
    version: openapi_3_1
server:
  port: 8097
  servlet:
    context-path: /softtek